import { NextIntlClientProvider, useMessages } from 'next-intl';
import './global.scss';
import { locales } from '../../navigation';

export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
  params: { locale },

}: {
  children: React.ReactNode;
  params: { locale: (typeof locales)[number] };
}) {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <NextIntlClientProvider messages={messages}>
      <body>{children}</body>
      </NextIntlClientProvider>

    </html>
  );
}
