import { NextIntlClientProvider, useMessages } from 'next-intl';
import './global.scss';
import { locales } from '../../navigation';
import { Inter as FontSans } from 'next/font/google';
// eslint-disable-next-line @nx/enforce-module-boundaries
import { cn } from '../../../../../libs/src/utils/utils';

export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};
export const inter = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
  weight: '400'
});

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: (typeof locales)[number] };
}) {
  const messages = useMessages();

  return (
    <html lang={locale}>
      <NextIntlClientProvider messages={messages}>
        <body
          className={cn(
            'min-h-screen bg-background font-sans antialiased',
            inter.className
          )}
        >
          {children}
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
